services:
  db:
    image: postgres:latest
    restart: always
    container_name: db
    ports:
      - "5432:5432" #op
    volumes:
      - ./db/db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootroot
      POSTGRES_DB: root