services:
  db:
    image: postgres:latest
    restart: always
    container_name: db
    ports:
      - "9020:5432" #op
    volumes:
      - ./db/db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: rootusers
      POSTGRES_PASSWORD: rootroot
      POSTGRES_DB: library
  
  crudservice:
    image: crudservice:latest
    build: 
      context: ./crudservice
      dockerfile: Dockerfile
    restart: always
    container_name: crudservice
    ports:
      - "3000:8000" #op
    depends_on:
      - db

  reportservice:
    image: reportservice:latest
    build: 
      context: ./reportservice
      dockerfile: Dockerfile
    restart: always
    container_name: reportservice
    ports:
      - "3001:8000" #op
    depends_on:
      - crudservice